### ISSUE TITLE
No way to Caveman in game

### ISSUE THREAD

**Issue by Unknown-Error4004** [PARTYMANX/partymod-thaw#2]
Doesn't seem to be a way to get off the board (Caveman) with the configurator as it is. As in I can't set any specific key to get off the board and am immediately stuck in game as it's the third mission on the first level.

**Comment by PARTYMANX** [comment]
This is a poorly documented part of the mod.  If you're in PS2 control mode, it should just be R1+L1 (spin left + spin right), as usual.  if you're not using that, switch/revert in the config should be bound to caveman, and nollie in the config is bound to... something PC/xbox-specific that I forget.

**Comment by Unknown-Error4004** [comment]
I was able to get it to Caveman with an Xbox controller setup, but then the controls are different when in skater mode. It won't let me grind out of walking, because it wants to tag (spraypaint) whenever I press Y instead, which is the default key for grinding too. Just weird

**Comment by PARTYMANX** [comment]
hah, that sounds like THAW alright.  yeah, grind is also tag in all versions

**Comment by PARTYMANX** [comment]
Speedrunners found no issue throughout a lot of activity in September, closing
